# Generated by Django 4.2.8 on 2024-06-19 01:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('input_name', models.CharField(max_length=200)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('input_type', models.CharField(choices=[('text', 'text'), ('select', 'select'), ('email', 'email'), ('checkbox', 'checkbox'), ('textarea', 'textarea'), ('date', 'date'), ('datetime', 'datetime'), ('time', 'time')], max_length=100)),
                ('date_type', models.CharField(choices=[('TODAY', 'TODAY'), ('CUSTOM', 'CUSTOM')], default='CUSTOM', max_length=10)),
                ('is_multiple_choice', models.BooleanField(default=False)),
                ('has_other_field', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=20), blank=True, size=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TableDataDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('position', models.IntegerField()),
                ('message', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('message', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.sections')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submission_id', models.UUIDField(default=uuid.uuid4)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('array_answer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=20), blank=True, size=20)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.sections')),
                ('submission_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.formsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FiledResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('array_answer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=20), blank=True, size=20)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.sections')),
                ('submission_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formsubmission')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.row'),
        ),
        migrations.CreateModel(
            name='DataFilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_title', models.CharField(max_length=200)),
                ('choice_id', models.IntegerField()),
                ('choice_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_choices', to='form.field')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('return_type', models.CharField(choices=[('MINUTES', 'MINUTES'), ('HOURS', 'HOURS'), ('SECONDS', 'SECONDS'), ('DIFFERENCE', 'DIFFERENCE'), ('SUM', 'SUM')], max_length=10)),
                ('field1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greater_calculation_field', to='form.field')),
                ('field2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smaller_calculation_field', to='form.field')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsFieldsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
    ]
