# Generated by Django 4.2.8 on 2024-05-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselor_id', models.IntegerField()),
                ('counselor_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_title', models.CharField(max_length=200)),
                ('choice_id', models.IntegerField()),
                ('choice_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
            ],
        ),
    ]
