# Generated by Django 4.2.8 on 2024-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='field',
            name='is_multiple_choice',
        ),
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.ManyToManyField(to='form.fieldoptions'),
        ),
    ]
