# Generated by Django 4.2.8 on 2024-02-28 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_formbuilder_created_at_formbuilder_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.sections'),
        ),
    ]
