# Generated by Django 4.2.8 on 2024-05-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_counselors_choicemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counselors',
        ),
    ]
