# Generated by Django 4.2.8 on 2024-08-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_fieldoptions_remove_field_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldanswers',
            name='array_answer',
        ),
        migrations.RemoveField(
            model_name='formfieldanswers',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formfieldanswers',
            name='section',
        ),
        migrations.AddField(
            model_name='formfieldanswers',
            name='json_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
