# Generated by Django 4.2.8 on 2024-05-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_delete_counselors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='choice_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_choices', to='form.field'),
        ),
    ]
