# Generated by Django 4.2.8 on 2024-02-28 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_row_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=20), size=20),
        ),
    ]
