# Generated by Django 4.2.8 on 2024-08-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_formfieldanswers_array_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FiledResponses',
        ),
    ]
