# Generated by Django 4.2.8 on 2024-08-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_delete_filedresponses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldoptions",
            old_name="title",
            new_name="key",
        ),
        migrations.RemoveField(
            model_name="field",
            name="date_type",
        ),
        migrations.AddField(
            model_name="field",
            name="is_multiple_choice",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fieldoptions",
            name="value",
            field=models.CharField(default="a", max_length=200),
            preserve_default=False,
        ),
    ]
