# Generated by Django 4.2.8 on 2024-02-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='title',
            field=models.CharField(default='Academic Level', max_length=200),
            preserve_default=False,
        ),
    ]
