# Generated by Django 4.2.8 on 2024-08-22 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0005_rename_title_fieldoptions_key_remove_field_date_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="is_disabled",
        ),
    ]
