# Generated by Django 4.2.8 on 2024-02-28 21:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_field_placeholder_field_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=20), blank=True, size=20),
        ),
    ]
