# Generated by Django 4.2.8 on 2024-09-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_remove_field_is_disabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatedFields',
        ),
    ]
