# Generated by Django 4.2.8 on 2024-02-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_alter_field_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='choices',
        ),
    ]
