# Generated by Django 4.2.8 on 2024-02-28 22:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_remove_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=20), blank=True, default=[], size=20),
            preserve_default=False,
        ),
    ]
