# Generated by Django 4.2.8 on 2024-02-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_field_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=models.CharField(max_length=100),
        ),
    ]
