# Generated by Django 4.2.8 on 2024-02-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_alter_field_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='has_other_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
