# Generated by Django 4.2.8 on 2024-02-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_field_has_other_field_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='input_name',
        ),
    ]
