# Generated by Django 4.2.8 on 2024-03-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_rename_name_field_input_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
