# Generated by Django 4.2.8 on 2024-03-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_formfieldanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='date_type',
            field=models.CharField(choices=[('TODAY', 'TODAY'), ('CUSTOM', 'CUSTOM')], default='CUSTOM', max_length=10),
        ),
    ]
