# Generated by Django 4.2.8 on 2024-03-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_formsubmission_field_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='submission',
        ),
    ]
