# Generated by Django 4.2.8 on 2024-03-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_remove_field_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.formsubmission'),
        ),
    ]
