# Generated by Django 4.2.8 on 2024-03-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_remove_field_submission_formfieldanswers_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('MINUTES', 'MINUTES'), ('HOURS', 'HOURS'), ('SECONDS', 'SECONDS'), ('DIFFERENCE', 'DIFFERENCE'), ('SUM', 'SUM')], max_length=10)),
                ('field1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greater_calculation_field', to='form.field')),
                ('field2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smaller_calculation_field', to='form.field')),
            ],
        ),
    ]
