# Generated by Django 4.2.8 on 2024-03-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_calculatedfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldanswers',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
