# Generated by Django 4.2.8 on 2024-03-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_alter_formfieldanswers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedfields',
            name='name',
            field=models.CharField(default='Session Time', max_length=100),
            preserve_default=False,
        ),
    ]
