# Generated by Django 4.2.8 on 2024-03-29 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_calculatedfields_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldanswers',
            name='submission',
        ),
    ]
