# Generated by Django 4.2.8 on 2024-03-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_remove_formfieldanswers_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfieldanswers',
            name='submission_id',
            field=models.UUIDField(default='b1432e80-6a42-4437-a246-8e852b4b7cda'),
            preserve_default=False,
        ),
    ]
