# Generated by Django 4.2.8 on 2024-04-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0027_datafiltersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafiltersettings',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder'),
        ),
    ]
