# Generated by Django 4.2.8 on 2024-04-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0028_alter_datafiltersettings_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDataDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
    ]
