# Generated by Django 4.2.8 on 2024-04-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_tabledatadisplaysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldanswers',
            name='date_added',
        ),
    ]
