# Generated by Django 4.2.8 on 2024-04-09 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_remove_formfieldanswers_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldanswers',
            name='submission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formsubmission'),
        ),
    ]
