# Generated by Django 4.2.8 on 2024-04-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0033_formfieldanswers_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='date_time',
            field=models.DateField(),
        ),
    ]
