# Generated by Django 4.2.8 on 2024-04-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0034_alter_formsubmission_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='date_time',
            new_name='date',
        ),
    ]
