# Generated by Django 4.2.8 on 2024-04-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_alter_formfieldanswers_submission_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfieldanswers',
            old_name='submission_id',
            new_name='submission_ref',
        ),
    ]
