# Generated by Django 4.2.8 on 2024-04-09 15:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0037_rename_submission_id_formfieldanswers_submission_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiledResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('array_answer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, size=20), blank=True, size=20)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.sections')),
                ('submission_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.formsubmission')),
            ],
        ),
    ]
