# Generated by Django 4.2.8 on 2024-04-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0038_filedresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedresponses',
            name='submission_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.formsubmission'),
            preserve_default=False,
        ),
    ]
