# Generated by Django 4.2.8 on 2024-12-04 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(to='form.field')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='TableDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ManyToManyField(to='form.field')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
        migrations.CreateModel(
            name='CalculatedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greater_field', to='form.field')),
                ('field_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smaller_field', to='form.field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formbuilder')),
            ],
        ),
    ]
